### ISSUE TITLE
The app doesn't remember the state 

### ISSUE THREAD

**Issue by petrvecera** [cohstats/coh3-stats-desktop-app#139]
https://github.com/tauri-apps/tauri-plugin-window-state

The issue will be somewhere here probably https://github.com/cohstats/coh3-stats-desktop-app/blob/master/src-tauri/src/main.rs#L72

**Comment by HeyZoos** [comment]
Mind if I take a crack at this?

**Comment by petrvecera** [comment]
Hi @HeyZoos sure! Please let me know if you need any assistance :)

**Comment by HeyZoos** [comment]
The issue seems to be related to how the application is closed.

1. Without making any changes, if you close the window using `Alt+F4` the window state is remembered correctly
2. If I re-enable the system title bar and close using the system `X` button, the window state is remembered correctly

I have not been able to figure out the right changes to make to `WindowTitleBar` to get it to close and retain state. What if I restore the system title bar for those 3 controls (and remove the icon from the custom title bar)? It looks a little funky but then the controls would behave as expected.

If you want to replicate restoring the system title bar, you have to clear out the data in the `%AppData%` folder since the Tauri Window State plugin also seems to persist the lack of system title bar.

###### Before
![image](https://github.com/user-attachments/assets/611ef27f-306a-4d05-8e86-335323feecce)

###### After
![image](https://github.com/user-attachments/assets/d7bc2172-1dde-4ad1-9d37-6d4e6e74b339)

**Comment by petrvecera** [comment]
Awesome findings! The default title bar is extremely ugly 😆 It looks to me as tauri state plugin bug - could be worth investigating if there aren't reports / or if we need to update it? 

Btw if it works with ALT + F4, isn't the problem in the way we execute the exit? With the X button? Can't we change that? But I assume this is what you tried and it doesn't work. 

Btw would it be possible to re-write the functionality of the tauri plugin ? In a way that when we click our X button, the state is saved to our config, and when we load the app, we read the log and re-size the app? I remember back in Electron days, we had to write this manually.

**Comment by petrvecera** [comment]
@HeyZoos  have you tried to this function https://github.com/cohstats/coh3-stats-desktop-app/blob/master/src/WindowTitleBar.tsx#L80

add 
```
import { saveWindowState, StateFlags } from "tauri-plugin-window-state-api";

saveWindowState(StateFlags.ALL);
```
https://github.com/tauri-apps/tauri-plugin-window-state?tab=readme-ov-file#usage

I think that should work - if it doesn't work it must be a bug in the plugin

**Comment by HeyZoos** [comment]
Yep that works :)

https://github.com/cohstats/coh3-stats-desktop-app/pull/166
