### ISSUE TITLE
Can I run the program without installing Edge WebView?

### ISSUE THREAD

**Issue by m0koko** [cohstats/coh3-stats-desktop-app#144]
I don't want to install Edge WebView on my computer. Is there a way to run the program without installing Edge WebView or can you make a version that doesn't require Edge WebView?

**Comment by petrvecera** [comment]
@m0koko  are you on Windows 7? Because on W10,11 the WebView should be part of the system. 
The WebView is necessary. I have created version which should have everything bundled together. You can download it from here https://github.com/cohstats/coh3-stats-desktop-app/releases/tag/1.5.2 (the full bundle) , please let me know if it works. 

Thanks 👍

**Comment by petrvecera** [comment]
Full bundle installer is available for download https://github.com/cohstats/coh3-stats-desktop-app/releases
